### ISSUE TITLE
Linux node crash on restart

### ISSUE THREAD

**Issue by n4kashu** [terafoundation/wallet#3]
Hi,

Linux node always crashes when restarted manually or for auto-update.

30000: 14:16:14.972: CLOSE 148.75.32.44:31567 *344c  *344c - Restart
Trace
    at CTransport.StopNode (/root/wallet/Source/core/block-loader.js:91:17)
    at global.RestartNode (/root/wallet/Source/core/code.js:218:12)
    at HTTPCaller.SetNetMode (/root/wallet/Source/core/html-server.js:444:9)
    at DoCommand (/root/wallet/Source/core/html-server.js:31:17)
    at IncomingMessage.<anonymous> (/root/wallet/Source/core/html-server.js:1156:21)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
30000: 14:16:14.974: ***************************************** RESTART!!!

**Comment by n4kashu** [comment]
the trace log is ok not a single issue with that..

**Comment by terafoundation** [comment]
Well, but I don't know the exact command to run the application on Linux. I need help.

**Comment by n4kashu** [comment]
installing pm2
npm install pm2 -g
and starting the node as service does the trick, any time it is down pm2 starts it
pm2 start run-node.js

**Comment by terafoundation** [comment]
This means that I do not need to do anything.
We'll write it in the instructions so that the startup is through pm2
yes?

**Comment by n4kashu** [comment]
correct
